### ISSUE TITLE
Any chance you can fix qemu to work on ubuntu 20.04

### ISSUE THREAD

**Issue by agroce** [SoftSec-KAIST/Eclipser#15]
Short version: ubuntu 20.04 uses a later glibc, which leads to a failure to build qemu according to the recipe in the v1.1 ("old Eclipser") release.  It looks like QEMU has fixed this, but presumably you are tagged to version 2.10.0 for good reasons.  Any chance you can incorporate the fix here https://patchwork.openembedded.org/patch/165581/ to get Eclipser 1.1 runnable on 20.04?

We're trying to make a DeepState (https://github.com/trailofbits/deepstate) release that bases off 20.04 instead of 18.04, and we'd like to keep the "old" Eclipser in the fuzzer stable (and add Eclipser 2.0 when we get a chance; the switch to relying on AFL parallel mode makes this non-trivial).  But when we try to build from docker, we run into:

```
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x64/linux-user/syscall.c:235:16: error: static declaration of 'gettid' follows non-static declaration
  235 | _syscall0(int, gettid)
      |                ^~~~~~
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x64/linux-user/syscall.c:164:13: note: in definition of macro '_syscall0'
  164 | static type name (void)   \
      |             ^~~~
In file included from /usr/include/unistd.h:1170,
                 from /home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x64/linux-user/syscall.c:27:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c:235:16: error: static declaration of 'gettid' follows non-static declaration
  235 | _syscall0(int, gettid)
      |                ^~~~~~
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c:164:13: note: in definition of macro '_syscall0'
  164 | static type name (void)   \
      |             ^~~~
In file included from /usr/include/unistd.h:1170,
                 from /home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c:27:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[2]: *** [/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x64/rules.mak:57: linux-user/syscall.o] Error 1
make[1]: *** [Makefile:173: subdir-x86_64-linux-user] Error 2
make[1]: Leaving directory '/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x64'
make: *** [Makefile:41: /home/user/Eclipser/Instrumentor/qemu/.compiled_x64] Error 1
make: *** Waiting for unfinished jobs....
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c: In function 'do_syscall':
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c:5962:29: warning: implicit declaration of function 'stime'; did you mean 'utime'? [-Wimplicit-function-declaration]
 5962 |             ret = get_errno(stime(&host_time));
      |                             ^~~~~
      |                             utime
/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/linux-user/syscall.c:5962:29: warning: nested extern declaration of 'stime' [-Wnested-externs]
make[2]: *** [/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86/rules.mak:57: linux-user/syscall.o] Error 1
make[1]: *** [Makefile:173: subdir-i386-linux-user] Error 2
make[1]: Leaving directory '/home/user/Eclipser/Instrumentor/qemu/qemu-2.3.0-pathcov-x86'
make: *** [Makefile:37: /home/user/Eclipser/Instrumentor/qemu/.compiled_x86] Error 1
```

There may be other issues preventing Eclipser 1.1 from running on 20.04 but this one seems fixable, if you have time.

**Comment by jchoi2022** [comment]
I will investigate this issue and try to make Eclipser v1.1 work on Ubuntu 20.04.

**Comment by agroce** [comment]
Don't stress about it; turns out most of the other tools DeepState uses ALSO fail on 20.04, except AFL and libFuzzer, so we're holding off moving until 20.04 is closer to the fuzzing community's horizon.

**Comment by jchoi2022** [comment]
It turned our that both qemu-2.10.0 (used in Eclipser 2.0) and qemu-2.3.0 (used in Eclipser 1.1) are affected by this issue. 

For Eclipser 2.0, commit c0ae7fd in 'dev' branch resolves this issue.

For Eclipser 1.1, we created a new branch 'v1.x' for the maintenance, and commit 67804d9 resolves this issue.

So please try 'v1.x' branch for Ubuntu 20.04.

**Comment by jchoi2022** [comment]
It turned our that both qemu-2.10.0 (used in Eclipser 2.0) and qemu-2.3.0 (used in Eclipser 1.1) are affected by this issue.

For Eclipser 2.0, commit c0ae7fd in 'dev' branch resolves this issue.

For Eclipser 1.1, we created a new branch 'v1.x' for the maintenance, and commit 75b1bc8 resolves this issue (there were some force pushes, so please ignore the other commits).

So you can try 'dev' and 'v1.x' branches for Ubuntu 20.04.

**Comment by jchoi2022** [comment]
Commit c0ae7fd is now merged into master, so you can use master branch for Eclipser v2.0 on Ubuntu 20.04.
